#1. Numpy

* 수학, 과학 계산용 패키지
* 성능: 파이썬의 list보다 빠름 -> ndarray
* 메모리 사이즈: 파이썬의 리스트보다 적은 메모리 사용


In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy

In [3]:
numpy

<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'>

In [4]:
import numpy as np

In [5]:
np

<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'>

###1-1. array(배열)
* 여러 값들의 그룹

In [6]:
list1 = [1, 2, 3, 4]
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(list1)
print(list2)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [7]:
print(type(list1))
print(type(list2))

<class 'list'>
<class 'list'>


In [8]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [10]:
print(type(arr)) # numpy.ndarray = n dimension array

<class 'numpy.ndarray'>


In [12]:
# 리스트를 ndarray로 생성하는 방법
arr1 = np.array(list1)
arr2 = np.array(list2)
print(arr1)
print(type(arr1))
print(arr2)
print(type(arr2))

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


### 1-2. array의 data타입
* ndarray는 list와 다르게 1개의 단일 데이터 타입만 허용

In [13]:
list1 = [1, 3.14, 'Python', '🤩', True]

In [16]:
list1

[1, 3.14, 'Python', '🤩', True]

In [17]:
list1[3]

'🤩'

In [20]:
arr1 = np.array([1, 2, 3, 4])

In [21]:
arr1

array([1, 2, 3, 4])

In [22]:
arr2 = np.array([1, 2, 3.14, 4]) 

In [23]:
arr2 # 큰 데이터 타입으로 바뀜

array([1.  , 2.  , 3.14, 4.  ])

In [24]:
arr3 = np.array([1, 2, 3.14, True])

In [25]:
arr3

array([1.  , 2.  , 3.14, 1.  ])

In [33]:
arr4 = np.array([1, 2, 3.14, True, 'apple'])

In [34]:
arr4

array(['1', '2', '3.14', 'True', 'apple'], dtype='<U32')

In [32]:
arr2 = np.array([1, 2, 3.14, 4], dtype = int) 
arr2

array([1, 2, 3, 4])

In [35]:
# arr4 = np.array([1, 2, 3.14, True, 'apple'], dtype = int) # error
arr4 = np.array([1, 2, 3.14, True, '1234'], dtype = int)
arr4

array([   1,    2,    3,    1, 1234])

###1-3. 슬라이싱(Slicing)
* 배열의 부분 선택

In [36]:
arr1 = np.array(['😍', '😎', '😜', '😊', '😃'])
arr1.shape

(5,)

In [41]:
print(arr1[0])
print(arr1[4])
print(arr1[-1])
print(arr1[-2])

😍
😃
😃
😊


In [44]:
print(arr1[0:3])
print(arr1[2:])
print(arr1[:3])

['😍' '😎' '😜']
['😜' '😊' '😃']
['😍' '😎' '😜']


In [45]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])
arr2d.shape

(3, 4)

In [47]:
arr2d[0, 2]

3

In [48]:
arr2d[2, 1]

10

In [50]:
# 0행을 가져오기
print(arr2d[0])
print(arr2d[0])
print(arr2d[0,:])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [52]:
# 0열을 가져오기
print(arr2d[:, 0])

[1 5 9]


In [53]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

###1-4. Fancy 인덱싱
* 범위가 아닌 특정 index의 집합의 값을 선택하여 추출하고 싶을 때 활용

In [55]:
arr1 = np.array([10, 23, 2, 6, 90, 85, 32, 66, 80])

In [56]:
idx = [1, 4, 6]

In [57]:
arr1[idx]

array([23, 90, 32])

In [58]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [59]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 1-5. Boolean 인덱싱
* 조건 필터링을 통하여 Boolean 값을 이용한 색인

In [60]:
arr1 = np.array(['😍', '😎', '😜', '😊', '😃'])
selValue = [True, True, False, False, True]

In [61]:
arr1[selValue]

array(['😍', '😎', '😃'], dtype='<U1')

In [62]:
selValue = [True, True, False]

In [64]:
# arr1[selValue] # IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3

In [65]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [66]:
arr2d > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [67]:
arr2d < 7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [68]:
arr2d[arr2d > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [69]:
arr2d[arr2d < 7]

array([1, 2, 3, 4, 5, 6])

# 2. 행렬 연산

###2-1. 연산자

In [71]:
# 덧셈 연산
a = np.array([[1, 2, 3], 
             [2, 3, 4]])
b = np.array([[3, 4, 5],
             [1, 2, 3]])

In [73]:
# shape가 같아야 함
# 같은 position끼리 연산 
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [74]:
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [75]:
# 곱셈 연산
a = np.array([[1, 2, 3], 
             [2, 3, 4]])
b = np.array([[3, 4, 5],
             [1, 2, 3]])

In [76]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [77]:
# 나눗셈 연산
a = np.array([[1, 2, 3], 
             [2, 3, 4]])
b = np.array([[3, 4, 5],
             [1, 2, 3]])

In [78]:
a / b

array([[0.33333333, 0.5       , 0.6       ],
       [2.        , 1.5       , 1.33333333]])

In [79]:
# dot product(내적)
# 맞닿는 shape가 같아야 함
# 결과 행렬은 떨어져 있는 shape의 형태
a = np.array([[1, 2, 3],
              [1, 2, 3],
              [2, 3, 4]])
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [80]:
a.shape, b.shape

((3, 3), (3, 2))

In [81]:
print((1*1+2*3+3*5), (1*2+2*4+3*6))
print((1*1+2*3+3*5), (1*2+2*4+3*6))
print((2*1+3*3+4*5), (2*2+3*4+4*6))

22 28
22 28
31 40


In [84]:
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

###2-2. arange
* 순차적인 값을 생성할 때 사용

In [85]:
arr1 = range(1, 11) # range: 표준 함수

In [86]:
arr1

range(1, 11)

In [87]:
for i in arr1:
    print(i, end = ' ')

1 2 3 4 5 6 7 8 9 10 

In [90]:
arr2 = np.arange(1, 11) # arange: 라이브러리 함수

In [91]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
for i in arr2:
    print(i, end = ' ')

1 2 3 4 5 6 7 8 9 10 

###2-3. sort(정렬)

In [94]:
arr1 = np.array([1, 10, 5, 7, 2, 4, 3, 6, 8, 9])

In [95]:
arr1

array([ 1, 10,  5,  7,  2,  4,  3,  6,  8,  9])

In [96]:
np.sort(arr1) # 기본적으로 오름차순 정렬

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
np.sort(arr1)[::-1] # 내림차순 

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [104]:
li1 = [1, 10, 5, 7, 2, 4, 3, 6, 8, 9]

In [105]:
li1.sort()

In [106]:
li1 # 정렬된 결과를 유지

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [107]:
arr1 # 정렬된 결과를 유지하지 않음

array([ 1, 10,  5,  7,  2,  4,  3,  6,  8,  9])

In [108]:
result = np.sort(arr1)

In [109]:
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
arr2d = np.array([[11, 10, 12, 9],
                  [3, 1, 4, 2],
                  [5, 6, 7, 8]])

In [111]:
arr2d.shape

(3, 4)

In [112]:
# 행 정렬
np.sort(arr2d, axis = 0)

array([[ 3,  1,  4,  2],
       [ 5,  6,  7,  8],
       [11, 10, 12,  9]])

In [113]:
# 열 정렬
np.sort(arr2d, axis = 1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [114]:
# 축의 마지막 방향 (2차원에서는 열, 3차원에서는 다른 축방향)
np.sort(arr2d, axis = -1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

###2-4. 숫자의 단일 연산

In [116]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[3, 3, 3],
              [3, 3, 3]])

In [118]:
a + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [119]:
a + b

array([[4, 5, 6],
       [7, 8, 9]])

In [120]:
a - 3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [121]:
a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [122]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])